version: '3'

services:
  db:
    image: mysql:5.7
    container_name: member-manager-mysql
    restart: always
    platform: linux/amd64
    ports:
      - 3306:3306
    networks:
      - db-net
    volumes:
      - member-manager-db-data:/etc/data
    environment:
      MYSQL_DATABASE: member_manager
      MYSQL_ROOT_PASSWORD: member1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: member
      MYSQL_PASSWORD: m1234
      TZ: Asia/Seoul
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci" ]
  web:
    container_name: member-manager-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - db-net
    depends_on:
      - db

networks:
  db-net:
    driver: bridge

volumes:
  member-manager-db-data: